name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Dar permisos a gradlew
        working-directory: APK/NotificationReader2
        run: chmod +x ./gradlew

      - name: Compilar APK Debug
        working-directory: APK/NotificationReader2
        run: ./gradlew assembleDebug

      - name: Subir APK generado
        uses: actions/upload-artifact@v4
        with:
          name: YapeDetector-debug-apk
          path: APK/NotificationReader2/app/build/outputs/apk/debug/*.apk
